WebSpeciliste/Controllers/CustomerController.cs
using Aggregates.Messages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Newtonsoft.Json;
using System.Collections.Generic;
using WebSpeciliste.Models;
using WebSpeciliste.services;
using WebSpeciliste.services.CustomerServices;

namespace WebSpeciliste.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomer _customerService;
        public CustomerController(ICustomer customerservice)
        {
            _customerService = customerservice;
        }
        public async Task<IActionResult> Indexs()
        {
            List<OfferDto> list = new List<OfferDto>();
            //List<SpecialistDto> list = new ();
            var res = await _customerService.GetCustomerOffersAsync<ResponseDto>("hhhh");
            if (res != null)
            {
                list = JsonConvert.DeserializeObject<List<OfferDto>>(Convert.ToString(res.result));
            }

            return View(list);
        }

        public async Task<IActionResult> Index([FromQuery] string? speciality, [FromQuery] string? location, [FromQuery] string? keyword)
        {
            List<OfferDto> list = new List<OfferDto>();
            //List<SpecialistDto> list = new ();
            //ViewBag.location = location;
            var res = await _customerService.GetOfferByLocationSpecialityKeywordAsync<ResponseDto>(speciality, location, keyword);
            if (res != null)
            {
                list = JsonConvert.DeserializeObject<List<OfferDto>>(Convert.ToString(res.result));
            }
            return View(list);
        }

        public async Task<IActionResult> OfferDetails(string? id)
        {
            var res = await _customerService.GetOneOfferAsync<ResponseDto>(id);
            OfferDto offer = new OfferDto();
            if (res != null)
            {
                offer = JsonConvert.DeserializeObject<OfferDto>(Convert.ToString(res.result));
            }
            return View(offer);
        }
        


        public async Task<IActionResult> CreateOffer()
        {
            //ViewBag.Error = new List<string>();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOffer(OfferDto model)
        {

            //var errors = ModelState.Values.SelectMany(v => v.Errors);
            //ViewBag.Error = errors;
            
            if (model.diploma) model.diploma = true;
            else model.diploma = false;

            if (ModelState.IsValid)
            {
                //model.created = DateTime.Now;
                var res = await _customerService.CreateOfferAsync<ResponseDto>(model);
                ViewBag.err = model.customerId;
                if (res != null & res.success)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
    }
}

WebSpeciliste/Controllers/SpecialistController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebSpeciliste.Models;
using WebSpeciliste.services.SpecialistsService;
using System.Collections.Generic;

namespace WebSpeciliste.Controllers
{
    public class SpecialistController : Controller
    {
        private readonly ISpecialist _SpecialistService;

        public SpecialistController(ISpecialist specialist)
        {
               _SpecialistService = specialist;
        }

        public async Task<IActionResult> Index()
        {
            List<SpecialistDto> list = new List<SpecialistDto>();
            //List<SpecialistDto> list = new ();
            var res  = await  _SpecialistService.GetAllSpecialistsAsync<ResponseDto>();
            if(res != null)
            {
                list = JsonConvert.DeserializeObject<List<SpecialistDto>>(Convert.ToString(res.result));
            }
            
             return View(list);
        }

        public async Task<IActionResult> SpecialistsCrud()
        {
            List<SpecialistDto> list = new List<SpecialistDto>();
            //List<SpecialistDto> list = new ();
            var res = await _SpecialistService.GetAllSpecialistsAsync<ResponseDto>();
            if (res != null)
            {
                list = JsonConvert.DeserializeObject<List<SpecialistDto>>(Convert.ToString(res.result));
            }

            return View(list);
        }

        public async Task<IActionResult> AddSpecialist()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSpecialist(SpecialistDto model)
        {

            if(ModelState.IsValid)
            {
                model.joined = DateTime.Now;
                //model.Email = "bzr@gmail.com";
                var res = await _SpecialistService.CreateSpecialistAsync<ResponseDto>(model);
                if (res != null && res.success)
                {
                    return RedirectToAction(nameof(SpecialistsCrud));
                }
            }
            
            return View(model);
        }


        public async Task<IActionResult> UpdateSpecialist(string specialistId)
        {
            List<SpecialistDto> list = new();
            var res = await _SpecialistService.GetOneSpecialistByIdAsync<ResponseDto>(specialistId);
            //ViewData["ok"] = res.errorMessages;
            if (res != null && res.success)
            {

                SpecialistDto specialist = JsonConvert.DeserializeObject<SpecialistDto>(Convert.ToString(res.result));
                return View(specialist);
            }
            return NotFound();

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateSpecialist(SpecialistDto model)
        {  
                var res = await _SpecialistService.UpdateSpecialistAsync<ResponseDto>(model.id,model);
                if (res != null && res.success)
                {
                    return RedirectToAction(nameof(SpecialistsCrud));
                }
            
            return View(model);
        }

        public async Task<IActionResult> DeleteSpecialist(string specialistId)
        {
            List<SpecialistDto> list = new();
            var res = await _SpecialistService.GetOneSpecialistByIdAsync<ResponseDto>(specialistId);
            if (res != null && res.success)
            {

                SpecialistDto specialist = JsonConvert.DeserializeObject<SpecialistDto>(Convert.ToString(res.result));
                return View(specialist);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteSpecialist(SpecialistDto model)
        {
            var res = await _SpecialistService.DeleteSpecialistAsync<ResponseDto>(model.id);
            if (res.success)
            {
                return RedirectToAction(nameof(SpecialistsCrud));
            }
            return View(model);
        }


    }
}

WebSpeciliste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FYS</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css"  />
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <div class="container-xxl bg-white p-0">
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
                    <h1 class="m-0 text-primary" >FYS</h1>
            </a>
            <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">
                    <a class="nav-item nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="nav-item nav-link" asp-area="" asp-controller="Specialist" asp-action="Index">Specialists</a>
                        <a class="nav-item nav-link" asp-area="" asp-controller="Specialist" asp-action="SpecialistsCrud">Specialists Crud</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="job-list.html" class="dropdown-item">Job List</a>
                            <a href="job-detail.html" class="dropdown-item">Job Detail</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="category.html" class="dropdown-item">Job Category</a>
                            <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                            <a href="404.html" class="dropdown-item">404</a>
                        </div>
                    </div>
                    <a href="contact.html" class="nav-item nav-link">Contact</a>
                </div>
                    <a class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block" asp-area="" asp-controller="Customer" asp-action="CreateOffer">Post An Offer<i class="fa fa-arrow-right ms-3"></i></a>
            </div>
        </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="container p-3">
                @RenderBody()
            </div>
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container p-5">
            &copy; 2022 - Find Your Specilist - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!--<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>-->
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/main.js"></script>


    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>